apiVersion: v1
kind: Service
metadata:
  name: preprocess-service
spec:
  selector:
    app: preprocess-service
  ports:
  - protocol: TCP
    port: 5002
    targetPort: 5001
  type: NodePort