apiVersion: v1
kind: Service
metadata:
  name: inference-service
spec:
  selector:
    app: inference-service
  ports:
  - protocol: TCP
    port: 5002
    targetPort: 5002
  type: NodePort