apiVersion: apps/v1
kind: Deployment
metadata:
  name: inference-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inference-service
  template:
    metadata:
      labels:
        app: inference-service
    spec:
      containers:
      - name: inference-service
        image: inference-service:latest
        ports:
        - containerPort: 5001